FROM node:25-alpine

WORKDIR /app

RUN apk add --no-cache git trivy
RUN apk add --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing snapraid

RUN git clone https://github.com/4rrgon/snapraid-web-ui .

RUN cd backend && npm install && \
    cd ../frontend && npm install

CMD ["sh"]
